### PR TITLE
Fixed message bubble colors

### PR DESCRIPTION
**Pull request by kremzli**
Apparently the "base" theme logic is reversed or something, i also did a few other fixes. Everything should be cash money now

We need to redo the screenshots, but im not sure if i just replace the files or not

### CODE REVIEW

**Comment by iruzo** [comment]
I tried the theme before and everything was just working fine, but I noticed something.

If you import the theme, and then import the other theme, the "base" theme keeps the first one, and, unless you uninstall and install the app again, it won't change.

Could you give a try to the one uploaded on the repo (but first, uninstall the app and install it again), then, reinstall the app again and then try the modified version ?

I have tried installing the app from f-droid, which I guess it shouldn't make a difference since I suppose it is the same binary/package as the one on Play Store.

Thanks in advance @kremzli

**Comment by kremzli** [comment]
Well i think that would be a bug, it should use the base in the theme file

**Comment by kremzli** [comment]
I will investigate

**Comment by kremzli** [comment]
With a fresh install, dark theme with "DARK" base works properly, but Latte with "LIGHT" base still doesnt work. The bases do change but for some reason dark themes with "DARK" base are broken in non fresh installs (i tried the fresh app in a work profile). I also tested my changes, Latte stays broken on the fresh install. I have both from the play store, but the fresh one is 5.5.3 while mine is 5.5.2 with no updates available (thanks google play, "updated 1 hour ago")

**Comment by kremzli** [comment]
So i will wait until play store remembers what up to date means and then i will test more

**Comment by iruzo** [comment]
Ah, I see, I'm using 5.5.1 because that is the latest one on f-droid. That is why we have different behaviors.

**Comment by kremzli** [comment]
Ok i never got an update by play store so i guess im going to ignore if updating would fix it or stay weird. I installed again (5.5.5) and light theme is just broken

**Comment by kremzli** [comment]
So instead ill keep these message bubble color changes (sent and received now look the same) and i will make an issue upstream that light theme doesnt work again

**Comment by iruzo** [comment]
Hi @kremzli, any update on the upstream issue about the light theme not working properly ? Just to know if this PR is still necessary or if we should modify it (or even discard it)

**Comment by kremzli** [comment]
nothing on the upstream issue https://github.com/simplex-chat/simplex-chat/issues/3842 
and i also stopped using simplex so i dont know of any changes. But i already modified this PR at the time to just make all the colors consistent, so if the logic behind how these work hasnt changed then merging this should be fine after testing it

**Comment by iruzo** [comment]
@kremzli We have implemented Whiskers on most of our repos, including this one. The themes have been changed to `themes/`, could you resolve the conflicts moving the files to that dir and adding the files missing on your branch so I can merge this PR ?

Thanks in advance !

**Comment by kremzli** [comment]
i think ill just do a different pull request

**Pull request closed without merging**
